# Generated by Django 4.0.4 on 2022-05-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('Formula', models.TextField(verbose_name='Formula')),
                ('description', models.TextField(verbose_name='description')),
                ('variables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_variables', to='CalculatorMaker.variables')),
            ],
        ),
    ]
